name: amgolink
description: "Smart Pharma Ecosystem"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  fl_chart: ^0.66.0
  flutter_animate: ^4.5.0
  animate_do: ^3.3.4
  font_awesome_flutter: ^10.6.0
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  glassmorphism: ^3.0.0
  intl: ^0.19.0
  percent_indicator: ^4.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true